### ISSUE TITLE
Widgets should ignore "Show Desktop / WIN_KEY + D"

### ISSUE THREAD

**Issue by supiantaril** [beyluta/WinWidgets#27]
if you select do not show over windows, then when you click on the button in the lower right corner "Show desktop", the widget is hidden along with all windows

**Comment by beyluta** [comment]
I will look into fixing this issue.

**Comment by beyluta** [comment]
This isn't possible due to how "WIN + D" works. It is always supposed to show the desktop no matter what.

"WIN + M" minimizes all windows. This command only minimizes the windows and thus can be safely ignored by WinWidgets whereas "WIN + D" just can't.
