### ISSUE TITLE
Custom widget properties

### ISSUE THREAD

**Issue by mateuszstalmach** [beyluta/WinWidgets#39]
Hello, I want to present calendar widget with specific settings, for example language. Can u make properties for widgets?

**Comment by beyluta** [comment]
Like a configuration file? That wil save the properties for a specific widget even when closed?

**Comment by mateuszstalmach** [comment]
I think, that this is good idea. Maybe, WinWidet must be in folder, with 4
files (JS file, CSS file, HTML file, and config file.

niedz., 23 lip 2023, 08:40 użytkownik Beyluta ***@***.***>
napisał:

**Comment by beyluta** [comment]
You can already put Widgets in a folder, (JS, CSS, HTML) and it should work. I will work on adding support for widget properties as a JSON file.

**Comment by beyluta** [comment]
I added the Widgets properties feature, I haven't yet had the time to update the binary on the release page, but you can build and run the project from the source code in Visual Studio to test the feature.

There's a brief explanation on how it works in the "Development" tab.

![image](https://github.com/beyluta/WinWidgets/assets/5099544/2df88dba-1057-44ca-8e4b-11328ce676e9)

**Comment by beyluta** [comment]
Added with #41
