### ISSUE TITLE
No luck in installing v1.3

### ISSUE THREAD

**Issue by Icaras12x** [beyluta/WinWidgets#42]
Hello friend, I wanted to test v1.3 but I'm having issues doing so.
After the process of installation, no shortcut gets created and no installed program. 
Windows 10 (all prerequisites checked)

**Comment by beyluta** [comment]
There's a chance I might have forgotten some .dll files. I noticed some issues when installing it on some arm64 versions of windows. I run some tests and will update the installer later today or tomorrow. I will keep you updated.

**Comment by beyluta** [comment]
@Icaras12x I updated the installer. Please uninstall the app (go to "Add or Remove Programs" and uninstall the current version) then download the new installer and make sure to check the "create desktop shortcut". It should work after this. Also please note that this version only works on x64 machines (most machines are x64), I am still working on the x86 (32-bit) and the ARM64 versions. Please tell me if it worked.

**Comment by Icaras12x** [comment]
> @Icaras12x I updated the installer. Please uninstall the app (go to "Add or Remove Programs" and uninstall the current version) then download the new installer and make sure to check the "create desktop shortcut". It should work after this. Also please note that this version only works on x64 machines (most machines are x64), I am still working on the x86 (32-bit) and the ARM64 versions. Please tell me if it worked.

I had a problem with my antivirus. Disabled it to run the installer but still can't get to make it work. Sometimes the program runs and crashes and I can't seem to find it in program files.
I'm using the x64 version since my own machine is x64.
I would love to help but I'm a web developer so I have no experience with c++/c# languages :/
