### ISSUE TITLE
"Always on top" should be persisted across restart

### ISSUE THREAD

**Issue by Yopai** [beyluta/WinWidgets#45]
* put a widget on the desktop
* toggle it as "Always on Top"
* disconnect from your session
* reconnect
* reopen WinWidgets

Result : the widget is not "Always on top" anymore.

What should be observed :

Like the position is, the "Always on top" status should be stored, and restored when the application is reopened.

I'll try to get some time to create a PR for this. As I'm not a .Net expert, any help about where the modification should be in the code would be appreciated.

**Comment by beyluta** [comment]
Shouldn't be that hard. You can save the state for every opened widget in the config file and write it back when opening the widgets. The base for this feature already exists, you only need to implement the logic to set the "always on top" property.

Take a look inside `Asset.Service.cs` inside the `/Services` folder. The following function can be used to overwrite the configuration file with new content.

```c#
/// <summary>
/// Overwrites the configuration file with new content
/// </summary>
/// <param name="content">Configuration object to be overwritten</param>
static public void OverwriteConfigurationFile(Configuration configuration)

**Comment by beyluta** [comment]
PR has been merged into development. I will create the installer for x64 machines and release a new version in the alpha 1.3.1 release page a little later today.
