### ISSUE TITLE
Request for feature : only reopen Widgets on startup

### ISSUE THREAD

**Issue by Yopai** [beyluta/WinWidgets#48]
When I mark the app as "run on startup", it shows fully on startup. It would be useful to have (the ability to have) only the widgets reloaded.

I'll try to get some time to develop and create a PR for this. As I'm not a .Net expert, any help about where the modification should be in the code would be appreciated.. Thanks ! :)

**Comment by beyluta** [comment]
Could this feature be related (or the same) as this one? 

#43

If it is: it has already been implemented and it's in the development branch of the project.

**Comment by Yopai** [comment]
It is indeed, thanks !
