### ISSUE TITLE
Show the current state of "Always on Top" in the menu

### ISSUE THREAD

**Issue by Yopai** [beyluta/WinWidgets#49]
The context menu only say "Toggle Always on Top"

It could use a check item to indicate the state :

   `Always on top` if it is not
   `✔ Always on top` if it is

**Comment by beyluta** [comment]
Awesome! tbh this is that kind of feature that I didn't know I needed. But now that I have seen it, I can't live without it. Thanks for the work 😄

**Comment by Yopai** [comment]
By the way, don't hesitate to modify, or instruct me to modify, some parts of my code, if you have some preferences or ideas.
I'm new to C# (and probably will use it only for WinWidgets :)), so I entirely assume not having certain habits you can have.
I'm not my code, so you can (constructively) criticize it without fear of hurting me.

**Comment by Yopai** [comment]
I'm really happy to help your project, as I'm looking for something like that for a long time.
(My use case : at work, we're asking to write down time we spent on each task; a Always on top widget will allow me to store constantly on which task I'm on, making it easy to compute time after that)

**Comment by beyluta** [comment]
> By the way, don't hesitate to modify, or instruct me to modify, some parts of my code, if you have some preferences or ideas. I'm new to C# (and probably will use it only for WinWidgets :)), so I entirely assume not having certain habits you can have. I'm not my code, so you can (constructively) criticize it without fear of hurting me.

Sure, thank you for contributing 😄. If there's anything wrong I'll let you know. I'm also not an expert when it comes to C#, I only use it for personal projects. At work we use other languages, thankfully they are close enough to C# so that some of the knowledge carries over.
