### ISSUE TITLE
GPU temperature elevated while WinWidgets is loaded

### ISSUE THREAD

**Issue by mantered** [beyluta/WinWidgets#62]
I'm having a problem with the GPU temperature going from 30°C at idle to over 50°C while WinWidgets is loaded.
Fresh install of the latest release on Windows 10. In task manager it shows minimal  GPU load but the temperature is climbing.

This is without any widgets visible, just the app minimized in the tray. If I quit the app the temperature is back to normal.
Is this normal ? I've only notice-it because of the GPU fan being noisier after I installed WinWidgets.

![gpu](https://github.com/beyluta/WinWidgets/assets/33768647/819a8b58-ce10-490d-9751-bc6eea8bcc14)

**Comment by beyluta** [comment]
It's hard to say. The temperatures didn't change very much for me when I started up WinWidgets. What are you PC specs?

**Comment by beyluta** [comment]
Could you try running WinWidgets with this option disabled?

![image](https://github.com/beyluta/WinWidgets/assets/5099544/f6e3efc8-bd1a-43c3-bd5e-89a568933ff8)

It is a DirectX feature that accesses the state of the graphics device. To my knowledge, it is the only feature that uses the GPU directly in WinWidgets. The function in question can be viewed from the WinWidgetsCore Repository:
https://github.com/beyluta/WinWidgetsCore/blob/main/main.cpp

**Comment by mantered** [comment]
The temperature problem is still there with that option disabled. I did a clean re-install of the GPU drivers but nothing changed.
It's weird that the GPU usage is 0% but GPU Clock/Mem is not going down when WinWidgetsis minimized to tray.
Also the GPU power draw is 62W and goes down to 15W after I exit WinWidgets.

![gfx](https://github.com/beyluta/WinWidgets/assets/33768647/3c59b0e8-e877-496a-8a4d-bc886c7dac5c)

**Comment by beyluta** [comment]
Have been testing it on my own PC. Ryzen 7 5800x and RTX 4060Ti, I haven't noticed such a drastic spike in temperatures. I noticed a spike of 2 degrees Celcius when I close and open WinWidgets, but this could also be weird randomness.

**Comment by mantered** [comment]
Ok, it seems this is a problem only with my 1080ti system. I cannot replicate-it on other PCs.
